// TraditionalKnowledgeAttribution Component Exports
export { TraditionalKnowledgeAttribution } from './TraditionalKnowledgeAttribution';

// Type Exports
export type {
  TraditionalKnowledgeAttributionProps,
  AttributableContent,
  AttributionInformation,
  SourceInformation,
  TraditionalOwnership,
  SourceVerification,
  ProvenanceRecord,
  ResponsibleParty,
  EducationalAttribution,
  CommunityAcknowledgment,
  CulturalClassification,
  VerificationProvider,
  CrossReference,
  CommunityValidation,
  AcademicValidation,
  StepVerification,
  DocumentationRecord,
  ContactInformation,
  SourceAccessibility,
  TimePeriod,
  CredibilityAssessment,
  CredibilityCriteria,
  CustodianInformation,
  UsageGuidelines,
  TraditionalPermissions,
  CulturalProtocol,
  EducationalResource,
  TeachingProtocol,
  CommunityMember,
  MembershipVerification,
  TraditionalClassificationSystem,
  SharingPermissionInfo,
  AttributionProvider,
  AttributionType,
  SourceType,
  OwnershipType,
  VerificationStatus,
  VerificationMethod,
  ConfidenceLevel,
  EducationalLevel,
  AcknowledgmentType,
  AcknowledgmentScope,
  SacredPublicLevel,
  ProviderType,
  ValidationResult,
  ProtocolType,
} from './types/TraditionalKnowledgeAttributionTypes';
